[tool.poetry]
name = "pylint-single-element-destructuring"
version = "0.1.0"
description = ""
authors = ["d1618033"]

[tool.poetry.dependencies]
python = "^3.6"
astroid = "^2.3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
